[package]
name = "semaphore-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
blake = "2.0.2"
light-poseidon = "0.3.0"
num-bigint = "0.4.6"
thiserror = "2.0.12"

# arkworks
ark-ec = { version = "=0.5.0", default-features = false }
ark-ed-on-bn254 = { version = "=0.5.0", default-features = false }
ark-ff = { version = "=0.5.0", default-features = false }

# zk-kit
zk-kit-lean-imt = { git = "https://github.com/brech1/zk-kit.rust", package = "zk-kit-lean-imt", branch = "feat/generic-tree" }
